### ISSUE TITLE
Remaining issues

### ISSUE THREAD

**Issue by pbiggar** [darklang/darklang.com#8]

**Comment by pbiggar** [comment]
- [ ] Style the first paragraph
- [ ] tone down the more aggressive gradients
- [ ] style the form error
- [ ] style the form success
- [ ] fix the darklang icon (see branding folder in docs repo)
- [ ] ensure pinks and purples all match

**Comment by pbiggar** [comment]
- [ ] form button not in the form on paul's browser
- [ ]

**Comment by OceanOak** [comment]
**Updated remaining issues:**

- [ ] Fix the first join waitlist button ( on mobile )
- [ ] Fix the second join button (on very large screen) 
- [ ] Style sign up success message 
- [ ] Style sign up error message
- [ ] Experiment with different styling for the first paragraph
- [ ] Cleanup code (remove unnecessary styling)
- [ ] Remove some of the HTML manipulation from JS
- [ ] Ensure pinks and purples all match
